version: '3'

services:
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - nginx-proxy-net

  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    networks:
      - nginx-proxy-net

networks:
  nginx-proxy-net:
    driver: bridge
